<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.538">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Heksa Bintang Pamungkas (220204131)">
<meta name="dcterms.date" content="2024-01-17">

<title>Analisis Pengaruh Inflasi Dan Pertumbuhan Ekonomi Terhadap Kemiskinan Di Indonesia Tahun 2013-2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analisis Pengaruh Inflasi Dan Pertumbuhan Ekonomi Terhadap Kemiskinan Di Indonesia Tahun 2013-2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Heksa Bintang Pamungkas (220204131) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="poltekapp.jpg" class="img-fluid figure-img"></p>
<figcaption>Politeknik APP Jakarta</figcaption>
</figure>
</div>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar Belakang</h3>
<p>Negara berkembang umumnya menghadapi tantangan ekonomi seperti kemiskinan, tingkat inflasi tinggi, dan pertumbuhan ekonomi yang lambat. Kemiskinan di Indonesia menjadi masalah umum, mirip dengan kondisi di banyak negara berkembang, terutama yang memiliki populasi padat seperti Indonesia. Kemiskinan dianggap sebagai indikator penting untuk menilai kesehatan ekonomi suatu negara, bukan hanya sebagai permasalahan pribadi dan pemerintah, melainkan juga sebagai masalah bersama yang perlu ditekan bersama-sama.</p>
<p>Inflasi dianggap sebagai indikator kunci dalam perekonomian, di mana upaya untuk menjaga laju inflasi rendah dan stabil diupayakan untuk mencegah dampak negatif terhadap ekonomi secara keseluruhan. Inflasi dapat memiliki dampak positif dan negatif, dan ketidakstabilan inflasi dapat berkontribusi pada kenaikan harga barang dan jasa secara terus-menerus, meningkatkan tingkat kemiskinan di Indonesia.</p>
<p>Tingkat inflasi yang tinggi dapat menyebabkan sulitnya masyarakat memenuhi kebutuhan sehari-hari karena harga barang dan jasa yang tinggi, yang pada gilirannya dapat meningkatkan tingkat kemiskinan. Tingkat inflasi di Indonesia mengalami fluktuasi dari tahun ke tahun, dengan kenaikan signifikan pada tahun 2013 akibat kenaikan harga Bahan Bakar Minyak (BBM) bersubsidi.</p>
<p>Pertumbuhan ekonomi dianggap sebagai masalah jangka panjang yang penting bagi setiap negara. Setiap negara memiliki tujuan untuk mempercepat pertumbuhan ekonominya agar dapat mencapai kesejahteraan yang tinggi. Pertumbuhan ekonomi dianggap sebagai kunci keberhasilan perekonomian suatu negara, dan kegagalan dalam meningkatkan pertumbuhan ekonomi dapat menimbulkan masalah baru seperti tingginya tingkat kemiskinan. Oleh Karena itu Penelitian ini bertujuan untuk menganalisis pengaruh inflasi dan pertumbuhan ekonomi terhadap tingkat kemiskinan di Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang Lingkup</h3>
<p>Dalam artikel ini akan diberikan batasan yang akan mencakup tentang inflasi dan pertumbuhan ekonomi terhadap kemiskinan di Indonesia dan ruang lingkup penelitian ini yang hanya menggunakan data dalam kurun waktu 10 tahun (2013-2022). Kegiatan pengambilan data diperoleh melalui Website Kemendag dan Badan Pusat Statistik.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan Masalah</h3>
<p>Berdasarkan uraian latar belakang masalah diatas, maka terdapat beberapa indikator yang menjadi rumusan masalah dalam penelitian ini. Adapun rumusan masalah tersebut adalah sebagai berikut:</p>
<ol type="1">
<li>Apakah inflasi berpengaruh terhadap kemiskinan di Indonesia?</li>
<li>Apakah pertumbuhan ekonomi berpengaruh terhadap kemiskinan di Indonesia?</li>
</ol>
</section>
<section id="tujuan-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-penelitian"><span class="header-section-number">1.4</span> Tujuan Penelitian</h3>
<p>Berdasarkan uraian latar belakang, maka dapat disimpulkan bahwa tujuan diterbitkannya artikel ini adalah sebagai berikut:</p>
<ol type="1">
<li>Untuk Mengetahui apakah inflasi berpengaruh terhadap kemiskinan di Indonesia</li>
<li>Untuk mengetahui apakah pertumbuhan ekonomi berpengaruh terhadap kemiskinan di Indonesia</li>
</ol>
</section>
<section id="manfaat-penelitian" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="manfaat-penelitian"><span class="header-section-number">1.5</span> Manfaat Penelitian</h3>
<p>Penelitian ini akan memberikan pemahaman yang lebih mendalam tentang bagaimana inflasi dan pertumbuhan ekonomi berkontribusi terhadap tingkat kemiskinan di Indonesia. Hal ini dapat memberikan wawasan yang diperlukan untuk menyusun kebijakan yang lebih efektif dalam menangani masalah kemiskinan.</p>
</section>
<section id="package" class="level3" data-number="1.6">
<h3 data-number="1.6" class="anchored" data-anchor-id="package"><span class="header-section-number">1.6</span> Package</h3>
<p>Packages yang digunakan :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(WDI)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi Pustaka</h2>
<section id="inflasi" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="inflasi"><span class="header-section-number">2.1</span> Inflasi</h3>
<p>Boediono (2001:161) mendefinisikan inflasi sebagai suatu kecenderungan kenaikan harga secara umum dan terus-menerus. Untuk dianggap sebagai inflasi, kenaikan harga tidak hanya terjadi pada satu atau dua barang, melainkan meluas dan berdampak pada sebagian besar barang lainnya. Fluktuasi inflasi dapat mempengaruhi kegiatan perekonomian, dengan dampak utama berupa penurunan daya beli masyarakat karena nilai riil mata uang mengalami penurunan.</p>
<p>Mankiw (2006:194) menyatakan bahwa inflasi adalah hal yang biasa, namun terdapat variasi signifikan dalam tingkat kenaikan harga. Masyarakat sering menganggap inflasi tinggi sebagai masalah utama dalam perekonomian. Nanga (2005:247) membagi inflasi menjadi empat kategori berdasarkan tingkat keparahannya:</p>
<ol type="1">
<li>Inflasi Ringan: Tingkat inflasi yang masih dapat dikendalikan dan tidak mengganggu keadaan ekonomi secara serius. Inflasi ringan biasanya memiliki tingkat di bawah 10% per tahun.</li>
<li>Inflasi Sedang: Meskipun belum membahayakan kegiatan ekonomi secara keseluruhan, inflasi sedang dapat menurunkan kesejahteraan masyarakat dengan pendapatan tetap. Rentang inflasi sedang berkisar antara 10% hingga 30%.</li>
<li>Inflasi Berat: Inflasi yang sudah mengacaukan kondisi perekonomian. Pada tingkat inflasi berat, orang cenderung menyimpan barang karena mereka enggan menabung akibat bunga bank yang lebih rendah dari tingkat inflasi. Inflasi berat berkisar antara 30% hingga 100% per tahun.</li>
<li>Hyperinflasi:Tingkat inflasi yang sangat tinggi dan sulit dikendalikan bahkan dengan tindakan moneter dan fiskal. Hyperinflasi memiliki nilai di atas 100% per tahun dan dapat menyebabkan kerusakan parah pada perekonomian.</li>
</ol>
</section>
<section id="pertumbuhan-ekonomi" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="pertumbuhan-ekonomi"><span class="header-section-number">2.2</span> Pertumbuhan Ekonomi</h3>
<p>Pertumbuhan ekonomi, menurut Suryana (2005:5), dapat diartikan sebagai peningkatan Gross Domestic Product (GDP) atau Produk Domestik Regional Bruto (PDRB), tanpa memperhatikan sejauh mana peningkatan tersebut lebih besar atau lebih kecil dibandingkan pertumbuhan penduduk, dan tanpa memperhitungkan adanya perubahan dalam struktur ekonomi. Menurut Jhingan (2004:67), proses pertumbuhan ekonomi dipengaruhi oleh dua jenis faktor, yaitu faktor ekonomi dan non-ekonomi. Beberapa faktor ekonomi yang berpengaruh</p>
</section>
<section id="kemiskinan" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="kemiskinan"><span class="header-section-number">2.3</span> Kemiskinan</h3>
<p>Menurut Siregar dan Wahyuniarti (2008:27), kemiskinan dapat diidentifikasi ketika seseorang memiliki pendapatan atau akses yang relatif rendah terhadap barang dan jasa jika dibandingkan dengan rata-rata orang lain dalam perekonomian tersebut. Dalam konteks absolut, seseorang dianggap miskin apabila tingkat pendapatan atau standar hidupnya berada di bawah ambang batas subsistensi yang dapat diukur dengan garis kemiskinan. Menurut Bank Dunia (Rendra:2010), terdapat tiga faktor penyebab kemiskinan, yaitu:</p>
<p>1.Rendahnya Pendapatan dan Aset: Kemiskinan dapat disebabkan oleh pendapatan dan kepemilikan aset yang rendah untuk memenuhi kebutuhan dasar, seperti makanan, tempat tinggal, pakaian, kesehatan, dan pendidikan. 2. Ketidakmampuan Bersuara dan Ketiadaan Kekuatan: Kemiskinan juga dapat terkait dengan ketidakmampuan seseorang untuk bersuara dan kurangnya kekuatan dalam berinteraksi dengan institusi negara dan masyarakat. 3. Rentan terhadap Guncangan Ekonomi: Individu yang tidak mampu mengatasi guncangan ekonomi atau rentan terhadap perubahan kondisi ekonomi juga dapat mengalami kemiskinan.</p>
</section>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode Penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tahun</th>
<th>Inflasi</th>
<th>PDB (Miliar Rupiah)</th>
<th>Persentase Kemiskinan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2013</td>
<td>8,38</td>
<td>8.156.497,8</td>
<td>11,47</td>
</tr>
<tr class="even">
<td>2014</td>
<td>8,36</td>
<td>8.564.866,6</td>
<td>10,96</td>
</tr>
<tr class="odd">
<td>2015</td>
<td>3,35</td>
<td>8.982.517,1</td>
<td>11,13</td>
</tr>
<tr class="even">
<td>2016</td>
<td>3,02</td>
<td>9.434.613,4</td>
<td>10,70</td>
</tr>
<tr class="odd">
<td>2017</td>
<td>3,61</td>
<td>9.912.928,1</td>
<td>10,12</td>
</tr>
<tr class="even">
<td>2018</td>
<td>3,13</td>
<td>10.425.851,9</td>
<td>9,66</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>2,72</td>
<td>10.949.155,4</td>
<td>9,22</td>
</tr>
<tr class="even">
<td>2020</td>
<td>1,68</td>
<td>10.722.999,3</td>
<td>10,19</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>1,87</td>
<td>11.120.077,9</td>
<td>9,71</td>
</tr>
<tr class="even">
<td>2022</td>
<td>5,51</td>
<td>11.710.397,8</td>
<td>9,57</td>
</tr>
</tbody>
</table>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis data menggunakan analisis regresi linier berganda (multiple regression analysis), dan Metode analisis yang digunakan dalam penelitian ini adalah metode kuantitatif dan penjabaran deskriptif. Teknik analisis kuantitatif merupakan analisis yang dilakukan dengan perhitungan angka-angka yang faktor yang mempengaruhi inflasi dan pertumbuhan ekonomi terhadap kemiskinan di Indonesia. Metode deskriptif digunakan untuk membuat gambaran secara sistematis dan faktual mengenai gambaran perkembangan dari setiap variabel dan kemiskinan ekonomi selanjutnya pendekatan yang digunakan adalah kuantitatif dengan mengaplikasikan model regresi linier berganda.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Pada bagian ini dapat ditampilkan data yang telah dikumpulkan :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'C:/Dokumen/Tugas Metopel/Heksa Bintang Pamungkas'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">read_excel</span>(<span class="st">"metopel.xlsx"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
       X         Y     S
   &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
 1  8.38  8156498. 11.5 
 2  8.36  8564867. 11.0 
 3  3.35  8982517. 11.1 
 4  3.02  9434613. 10.7 
 5  3.61  9912928. 10.1 
 6  3.13 10425852.  9.66
 7  2.72 10949155.  9.22
 8  1.68 10722999. 10.2 
 9  1.87 11120078.  9.71
10  5.51 11710398.  9.57</code></pre>
</div>
</div>
<p>Diketahui :</p>
<p>X = Inflasi</p>
<p>Y = PDB Indonesia</p>
<p>S = Persentase Kemiskinan</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"metopel.xlsx"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat, <span class="fu">aes</span>(<span class="at">x=</span>X<span class="sc">+</span>Y, <span class="at">y=</span>S))<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">'blue'</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Plot Tingkat Kemiskinan di Indonesia"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Inflasi &amp; PDB"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Kemiskinan di Indonesia"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Sumber:  Badan Pusat Statistik (BPS) dan Kementerian Perdagangan (Kemendag)"</span>) <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresi ditunjukkan sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"metopel.xlsx"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(S<span class="sc">~</span>X<span class="sc">+</span>Y,<span class="at">data=</span>dat)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = S ~ X + Y, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.49116 -0.19232  0.09689  0.22006  0.34512 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.618e+01  1.335e+00  12.120 5.95e-06 ***
X           -9.569e-05  5.662e-02  -0.002   0.9987    
Y           -5.908e-07  1.173e-07  -5.039   0.0015 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3271 on 7 degrees of freedom
Multiple R-squared:  0.8545,    Adjusted R-squared:  0.8129 
F-statistic: 20.55 on 2 and 7 DF,  p-value: 0.001175</code></pre>
</div>
</div>
<p>Uji simultan (Uji F) dilakukan untuk menguji seberapa besar pengaruh dari variabel independen yaitu inflasi dan PDB Indonesia terhadap variabel dependen yaitu persentase kemiskinan. Berdasarkan hasil regresi diperoleh nilai F-statistic sebesar 20.55 dengan probabilitas 0.001175 (&gt; α=0,1). Sehingga variabel inflasi dan PDB Indonesia pengaruh signifikan terhadap tingkat kemiskinan Indonesia selama periode 2013-2022.</p>
<p>Nilai R² digunakan untuk menunjukkan seberapa besar pengaruh variabel independen terhadap variabel dependen. Berdasarkan pada tabel di atas, hasil nilai R² menunjukkan bahwa tingkat kemiskinan Indonesia dipengaruhi oleh variabel inflasi dan pertumbuhan ekonomi Indonesia sebesar 0.8545 atau 85,45%. Artinya sebesar 85,45% tingkat kemiskinan di Indonesia dipengaruhi oleh inflasi dan juga pertumbuhan ekonomi di Indonesia. Sedangkan sebanyak 14,55% dipengaruhi oleh variabel lain yang tidak termasuk dalam penelitian ini.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan data penelitian di atas membuktikan bahwa inflasi dan pertumbuhan ekonomi di Indonesia sangat berpengaruh secara signifikan terhadap tingkat kemiskinan di Indonesia. Dengan variabel independen yaitu inflasi dan pertumbuhan ekonomi di Indonesia yang menjadi faktor yang dapat mendorong naik dan turunnya variabel dependen yaitu tingkat kemiskinan di Indonesia. Melalui pengaruhnya terhadap variabel dependen, yaitu tingkat kemiskinan, inflasi dan pertumbuhan ekonomi menjadi faktor kunci yang perlu dipahami dalam konteks perencanaan dan implementasi kebijakan ekonomi di Indonesia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Badan Pusat Statistik. (2022). Retrieved January 17, 2024, from https://jatim.bps.go.id/indicator/23/344/1/persentase-penduduk-miskin-menurut-provinsi-.html</p>
<p>Kementrian Perdagangan. (2012-2021). Profil komoditas. Kementrian Perdagangan, 33. https://satudata.kemendag.go.id/data-informasi/perdagangan-dalam-negeri/produk-domestik-bruto</p>
<p>Kementrian Perdagangan. (2012-2021). Profil komoditas. Kementrian Perdagangan, 33. https://satudata.kemendag.go.id/data-informasi/perdagangan-dalam-negeri/inflasi-2020</p>
<p>Ningsih, D., &amp; Andiny, P. (2018). Analisis pengaruh inflasi dan pertumbuhan ekonomi terhadap kemiskinan di Indonesia. Jurnal samudra ekonomika, 2(1), 53-61.</p>
<p>Susanto, R., &amp; Pangesti, I. (2021). Pengaruh Inflasi Dan Pertumbuhan Ekonomi Terhadap Tingkat Kemiskinan Di Indonesia. JABE (Journal of Applied Business and Economic), 7(2), 271-278.</p>
<p>Simanungkalit, E. F. B. (2020). Pengaruh inflasi terhadap pertumbuhan ekonomi di Indonesia. Journal of Management: Small and Medium Enterprises (SMEs), 13(3), 327-340.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>